before_script:
  - ls
  - terraform --version
  - terraform init
  - aws sts get-caller-identity
  - TFVAR_FILE=infra.tfvars

stages:
  - plan
  - apply

build:
  stage: plan
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!!"
    - echo "plan start!!"
    - terraform plan -out tfplan -var-file="configurations/$TFVAR_FILE"
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - tfplan

deploy:
  stage: apply
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - echo "apply start!!"
    - terraform apply tfplan
  dependencies:
    - build
  when: manual

