before_script:
  - terraform --version
  - terraform init
  - aws sts get-caller-identity

stages:
  - plan
  - apply

build:
  stage: plan
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!!"
    - echo "plan start!!"
    - terraform plan -out ftplan

deploy:
  stage: apply
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
    - echo "apply start!!"
  when: manual
